// Auto-generated by Insimul export pipeline — do not edit manually.
#pragma once

#include "CoreMinimal.h"
#include "Blueprint/UserWidget.h"
#include "InsimulWorldMap.generated.h"

/** Map marker types for the world map overlay. */
UENUM(BlueprintType)
enum class EInsimulMapMarkerType : uint8
{
    Settlement,
    QuestObjective,
    QuestItem,
    NPC,
    Player
};

/** A single marker displayed on the world map. */
USTRUCT(BlueprintType)
struct FInsimulMapMarker
{
    GENERATED_BODY()

    UPROPERTY(EditAnywhere, BlueprintReadWrite) FString Id;
    UPROPERTY(EditAnywhere, BlueprintReadWrite) FString Label;
    UPROPERTY(EditAnywhere, BlueprintReadWrite) FVector2D WorldPosition = FVector2D::ZeroVector;
    UPROPERTY(EditAnywhere, BlueprintReadWrite) EInsimulMapMarkerType MarkerType = EInsimulMapMarkerType::Settlement;
    UPROPERTY(EditAnywhere, BlueprintReadWrite) FLinearColor Color = FLinearColor::White;
};

/** A road segment drawn on the world map canvas. */
USTRUCT(BlueprintType)
struct FInsimulMapRoad
{
    GENERATED_BODY()

    UPROPERTY(EditAnywhere, BlueprintReadWrite) TArray<FVector2D> Waypoints;
    UPROPERTY(EditAnywhere, BlueprintReadWrite) float Width = 2.f;
};

/**
 * Full-screen world map widget.
 *
 * Displays a top-down overview of the world with settlement markers,
 * road lines, quest markers, NPC positions, and a player arrow.
 * Supports pan (mouse drag) and zoom (mouse wheel) with configurable
 * zoom levels from the IR map screen configuration.
 *
 * Toggle with M key. Pauses the game and shows the cursor while open.
 */
UCLASS()
class INSIMULEXPORT_API UInsimulWorldMap : public UUserWidget
{
    GENERATED_BODY()

public:
    /** Initialize the map with world data. Call once after construction. */
    UFUNCTION(BlueprintCallable, Category = "Insimul|WorldMap")
    void InitializeMap(float InWorldSize, const TArray<float>& InZoomLevels);

    /** Add a marker to the map. */
    UFUNCTION(BlueprintCallable, Category = "Insimul|WorldMap")
    void AddMarker(const FInsimulMapMarker& Marker);

    /** Add a road segment to the map. */
    UFUNCTION(BlueprintCallable, Category = "Insimul|WorldMap")
    void AddRoad(const FInsimulMapRoad& Road);

    /** Update the player position and rotation on the map. */
    UFUNCTION(BlueprintCallable, Category = "Insimul|WorldMap")
    void UpdatePlayerPosition(FVector2D Position, float RotationDegrees);

    /** Remove all markers of a given type. */
    UFUNCTION(BlueprintCallable, Category = "Insimul|WorldMap")
    void ClearMarkersByType(EInsimulMapMarkerType Type);

    /** Toggle map visibility. Pauses game and shows cursor when open. */
    UFUNCTION(BlueprintCallable, Category = "Insimul|WorldMap")
    void ToggleMap();

    /** Whether the map is currently visible. */
    UFUNCTION(BlueprintPure, Category = "Insimul|WorldMap")
    bool IsMapOpen() const { return bIsOpen; }

protected:
    virtual void NativeConstruct() override;
    virtual void NativeTick(const FGeometry& MyGeometry, float InDeltaTime) override;
    virtual int32 NativePaint(const FPaintArgs& Args, const FGeometry& AllottedGeometry,
        const FSlateRect& MyCullingRect, FSlateWindowElementList& OutDrawElements,
        int32 LayerId, const FWidgetStyle& InWidgetStyle, bool bParentEnabled) const override;
    virtual FReply NativeOnMouseWheel(const FGeometry& InGeometry, const FPointerEvent& InMouseEvent) override;
    virtual FReply NativeOnMouseButtonDown(const FGeometry& InGeometry, const FPointerEvent& InMouseEvent) override;
    virtual FReply NativeOnMouseButtonUp(const FGeometry& InGeometry, const FPointerEvent& InMouseEvent) override;
    virtual FReply NativeOnMouseMove(const FGeometry& InGeometry, const FPointerEvent& InMouseEvent) override;

private:
    /** Convert world coordinates to map screen coordinates. */
    FVector2D WorldToMap(FVector2D WorldPos, const FGeometry& Geometry) const;

    /** Cycle to the next zoom level (direction: +1 zoom in, -1 zoom out). */
    void CycleZoom(int32 Direction);

    /** Apply pan/zoom clamping so the view stays within the world bounds. */
    void ClampPanOffset();

    /** Draw a single marker at its screen position. */
    void DrawMarker(const FInsimulMapMarker& Marker, const FGeometry& Geometry,
        FSlateWindowElementList& OutDrawElements, int32 LayerId) const;

    // ── State ──
    bool bIsOpen = false;
    bool bIsDragging = false;
    FVector2D DragStart = FVector2D::ZeroVector;
    FVector2D PanOffset = FVector2D::ZeroVector;
    float WorldSize = 1000.f;
    int32 CurrentZoomIndex = 1;
    TArray<float> ZoomLevels;

    // ── Data ──
    TArray<FInsimulMapMarker> Markers;
    TArray<FInsimulMapRoad> Roads;
    FVector2D PlayerPosition = FVector2D::ZeroVector;
    float PlayerRotation = 0.f;

    // ── Visual constants ──
    static constexpr float MAP_PADDING = 40.f;
    static constexpr float MARKER_SIZE = 8.f;
    static constexpr float PLAYER_ARROW_SIZE = 12.f;
    static constexpr float ROAD_LINE_THICKNESS = 2.f;
};
