// Auto-generated by Insimul export pipeline — do not edit manually.
#include "InsimulMainMenuWidget.h"
#include "Blueprint/WidgetTree.h"
#include "Components/CanvasPanel.h"
#include "Components/CanvasPanelSlot.h"
#include "Components/VerticalBox.h"
#include "Components/VerticalBoxSlot.h"
#include "Components/TextBlock.h"
#include "Components/Button.h"
#include "Components/Image.h"
#include "Components/Spacer.h"
#include "Kismet/GameplayStatics.h"
#include "Kismet/KismetSystemLibrary.h"
#include "Engine/Texture2D.h"

void UInsimulMainMenuWidget::NativeConstruct()
{
    Super::NativeConstruct();

    RootCanvas = WidgetTree->ConstructWidget<UCanvasPanel>(UCanvasPanel::StaticClass(), TEXT("RootCanvas"));
    WidgetTree->RootWidget = RootCanvas;

    // Background image
    BackgroundImage = WidgetTree->ConstructWidget<UImage>(UImage::StaticClass(), TEXT("BackgroundImage"));
    UCanvasPanelSlot* BgSlot = RootCanvas->AddChildToCanvas(BackgroundImage);
    BgSlot->SetAnchors(FAnchors(0.f, 0.f, 1.f, 1.f));
    BgSlot->SetOffsets(FMargin(0.f));
    BackgroundImage->SetColorAndOpacity(FLinearColor(0.1f, 0.1f, 0.15f, 1.f));

    BuildMainMenuPanel();
    BuildSettingsPanel();
    ShowMainMenu();
}

void UInsimulMainMenuWidget::SetTitle(const FString& InTitle)
{
    GameTitle = InTitle;
    if (TitleText)
    {
        TitleText->SetText(FText::FromString(GameTitle));
    }
}

void UInsimulMainMenuWidget::SetBackgroundImage(const FString& AssetPath)
{
    BackgroundAssetPath = AssetPath;
    if (!AssetPath.IsEmpty() && BackgroundImage)
    {
        UTexture2D* Tex = Cast<UTexture2D>(StaticLoadObject(UTexture2D::StaticClass(), nullptr, *AssetPath));
        if (Tex)
        {
            BackgroundImage->SetBrushFromTexture(Tex);
        }
    }
}

void UInsimulMainMenuWidget::BuildMainMenuPanel()
{
    MainMenuPanel = WidgetTree->ConstructWidget<UVerticalBox>(UVerticalBox::StaticClass(), TEXT("MainMenuPanel"));
    UCanvasPanelSlot* Slot = RootCanvas->AddChildToCanvas(MainMenuPanel);
    Slot->SetAnchors(FAnchors(0.5f, 0.5f, 0.5f, 0.5f));
    Slot->SetAlignment(FVector2D(0.5f, 0.5f));
    Slot->SetSize(FVector2D(400.f, 500.f));

    // Title
    TitleText = WidgetTree->ConstructWidget<UTextBlock>(UTextBlock::StaticClass(), TEXT("TitleText"));
    TitleText->SetText(FText::FromString(GameTitle.IsEmpty() ? TEXT("Insimul") : *GameTitle));
    FSlateFontInfo TitleFont = TitleText->GetFont();
    TitleFont.Size = 48;
    TitleText->SetFont(TitleFont);
    TitleText->SetJustification(ETextJustify::Center);
    TitleText->SetColorAndOpacity(FSlateColor(FLinearColor::White));
    UVerticalBoxSlot* TitleSlot = MainMenuPanel->AddChildToVerticalBox(TitleText);
    TitleSlot->SetHorizontalAlignment(HAlign_Center);
    TitleSlot->SetPadding(FMargin(0.f, 0.f, 0.f, 40.f));

    // Spacer
    USpacer* Spacer = WidgetTree->ConstructWidget<USpacer>(USpacer::StaticClass(), TEXT("MenuSpacer"));
    Spacer->SetSize(FVector2D(1.f, 20.f));
    MainMenuPanel->AddChildToVerticalBox(Spacer);

    // Menu buttons
    UButton* NewGameBtn = CreateMenuButton(TEXT("New Game"), MainMenuPanel);
    NewGameBtn->OnClicked.AddDynamic(this, &UInsimulMainMenuWidget::OnNewGameClicked);

    UButton* ContinueBtn = CreateMenuButton(TEXT("Continue"), MainMenuPanel);
    ContinueBtn->OnClicked.AddDynamic(this, &UInsimulMainMenuWidget::OnContinueClicked);

    UButton* SettingsBtn = CreateMenuButton(TEXT("Settings"), MainMenuPanel);
    SettingsBtn->OnClicked.AddDynamic(this, &UInsimulMainMenuWidget::OnSettingsClicked);

    UButton* QuitBtn = CreateMenuButton(TEXT("Quit"), MainMenuPanel);
    QuitBtn->OnClicked.AddDynamic(this, &UInsimulMainMenuWidget::OnQuitClicked);
}

void UInsimulMainMenuWidget::BuildSettingsPanel()
{
    SettingsPanel = WidgetTree->ConstructWidget<UVerticalBox>(UVerticalBox::StaticClass(), TEXT("SettingsPanel"));
    UCanvasPanelSlot* Slot = RootCanvas->AddChildToCanvas(SettingsPanel);
    Slot->SetAnchors(FAnchors(0.5f, 0.5f, 0.5f, 0.5f));
    Slot->SetAlignment(FVector2D(0.5f, 0.5f));
    Slot->SetSize(FVector2D(500.f, 600.f));

    // Settings title
    UTextBlock* SettingsTitle = WidgetTree->ConstructWidget<UTextBlock>(UTextBlock::StaticClass(), TEXT("SettingsTitle"));
    SettingsTitle->SetText(FText::FromString(TEXT("Settings")));
    FSlateFontInfo Font = SettingsTitle->GetFont();
    Font.Size = 36;
    SettingsTitle->SetFont(Font);
    SettingsTitle->SetJustification(ETextJustify::Center);
    SettingsTitle->SetColorAndOpacity(FSlateColor(FLinearColor::White));
    UVerticalBoxSlot* TitleSlot = SettingsPanel->AddChildToVerticalBox(SettingsTitle);
    TitleSlot->SetHorizontalAlignment(HAlign_Center);
    TitleSlot->SetPadding(FMargin(0.f, 0.f, 0.f, 30.f));

    // Category labels (placeholder — full settings require Slate sliders/dropdowns)
    TArray<FString> Categories = { TEXT("Audio"), TEXT("Graphics"), TEXT("Controls"), TEXT("Language") };
    for (const FString& Cat : Categories)
    {
        UTextBlock* Label = WidgetTree->ConstructWidget<UTextBlock>(UTextBlock::StaticClass());
        Label->SetText(FText::FromString(Cat));
        FSlateFontInfo LabelFont = Label->GetFont();
        LabelFont.Size = 20;
        Label->SetFont(LabelFont);
        Label->SetColorAndOpacity(FSlateColor(FLinearColor(0.8f, 0.8f, 0.8f)));
        UVerticalBoxSlot* LabelSlot = SettingsPanel->AddChildToVerticalBox(Label);
        LabelSlot->SetHorizontalAlignment(HAlign_Center);
        LabelSlot->SetPadding(FMargin(0.f, 10.f, 0.f, 10.f));
    }

    // Back button
    UButton* BackBtn = CreateMenuButton(TEXT("Back"), SettingsPanel);
    BackBtn->OnClicked.AddDynamic(this, &UInsimulMainMenuWidget::OnSettingsBackClicked);
}

UButton* UInsimulMainMenuWidget::CreateMenuButton(const FString& Label, UVerticalBox* Parent)
{
    UButton* Btn = WidgetTree->ConstructWidget<UButton>(UButton::StaticClass());
    Btn->SetBackgroundColor(FLinearColor(0.15f, 0.15f, 0.2f, 0.9f));

    UTextBlock* BtnText = WidgetTree->ConstructWidget<UTextBlock>(UTextBlock::StaticClass());
    BtnText->SetText(FText::FromString(Label));
    FSlateFontInfo BtnFont = BtnText->GetFont();
    BtnFont.Size = 22;
    BtnText->SetFont(BtnFont);
    BtnText->SetJustification(ETextJustify::Center);
    BtnText->SetColorAndOpacity(FSlateColor(FLinearColor::White));
    Btn->AddChild(BtnText);

    UVerticalBoxSlot* BtnSlot = Parent->AddChildToVerticalBox(Btn);
    BtnSlot->SetHorizontalAlignment(HAlign_Center);
    BtnSlot->SetPadding(FMargin(0.f, 8.f, 0.f, 8.f));

    return Btn;
}

void UInsimulMainMenuWidget::ShowMainMenu()
{
    MainMenuPanel->SetVisibility(ESlateVisibility::Visible);
    SettingsPanel->SetVisibility(ESlateVisibility::Collapsed);
}

void UInsimulMainMenuWidget::ShowSettings()
{
    MainMenuPanel->SetVisibility(ESlateVisibility::Collapsed);
    SettingsPanel->SetVisibility(ESlateVisibility::Visible);
}

// ── Button handlers ──

void UInsimulMainMenuWidget::OnNewGameClicked()
{
    UGameplayStatics::OpenLevel(this, TEXT("GameLevel"));
}

void UInsimulMainMenuWidget::OnContinueClicked()
{
    // Load saved game — if no save exists, fall through to new game
    if (UGameplayStatics::DoesSaveGameExist(TEXT("InsimulSave"), 0))
    {
        UGameplayStatics::OpenLevel(this, TEXT("GameLevel"));
    }
}

void UInsimulMainMenuWidget::OnSettingsClicked()
{
    ShowSettings();
}

void UInsimulMainMenuWidget::OnQuitClicked()
{
    UKismetSystemLibrary::QuitGame(this, nullptr, EQuitPreference::Quit, true);
}

void UInsimulMainMenuWidget::OnSettingsBackClicked()
{
    ShowMainMenu();
}

void UInsimulMainMenuWidget::OnApplySettingsClicked()
{
    // Settings are applied via GameUserSettings in a full implementation
    ShowMainMenu();
}
