// Auto-generated by Insimul export pipeline — do not edit manually.
#include "InsimulPauseMenuWidget.h"
#include "Blueprint/WidgetTree.h"
#include "InsimulSaveGame.h"
#include "Components/CanvasPanel.h"
#include "Components/CanvasPanelSlot.h"
#include "Components/VerticalBox.h"
#include "Components/VerticalBoxSlot.h"
#include "Components/TextBlock.h"
#include "Components/Button.h"
#include "Components/Image.h"
#include "Components/Spacer.h"
#include "Kismet/GameplayStatics.h"

void UInsimulPauseMenuWidget::NativeConstruct()
{
    Super::NativeConstruct();

    RootCanvas = WidgetTree->ConstructWidget<UCanvasPanel>(UCanvasPanel::StaticClass(), TEXT("RootCanvas"));
    WidgetTree->RootWidget = RootCanvas;

    // Semi-transparent background overlay
    UImage* Overlay = WidgetTree->ConstructWidget<UImage>(UImage::StaticClass(), TEXT("Overlay"));
    UCanvasPanelSlot* OvSlot = RootCanvas->AddChildToCanvas(Overlay);
    OvSlot->SetAnchors(FAnchors(0.f, 0.f, 1.f, 1.f));
    OvSlot->SetOffsets(FMargin(0.f));
    Overlay->SetColorAndOpacity(FLinearColor(0.f, 0.f, 0.f, 0.6f));

    BuildMainPanel();
    SetVisibility(ESlateVisibility::Collapsed);
}

bool UInsimulPauseMenuWidget::TogglePauseMenu()
{
    if (GetVisibility() == ESlateVisibility::Visible)
    {
        ClosePauseMenu();
        return false;
    }

    ShowMainPanel();
    SetVisibility(ESlateVisibility::Visible);
    SetPaused(true);
    return true;
}

void UInsimulPauseMenuWidget::ClosePauseMenu()
{
    SetVisibility(ESlateVisibility::Collapsed);
    SetPaused(false);
}

void UInsimulPauseMenuWidget::SetPaused(bool bPause)
{
    APlayerController* PC = GetOwningPlayer();
    if (!PC) return;

    UGameplayStatics::SetGamePaused(this, bPause);
    if (bPause)
    {
        PC->SetShowMouseCursor(true);
        PC->SetInputMode(FInputModeUIOnly());
    }
    else
    {
        PC->SetShowMouseCursor(false);
        PC->SetInputMode(FInputModeGameOnly());
    }
}

void UInsimulPauseMenuWidget::BuildMainPanel()
{
    MainPanel = WidgetTree->ConstructWidget<UVerticalBox>(UVerticalBox::StaticClass(), TEXT("MainPanel"));
    UCanvasPanelSlot* Slot = RootCanvas->AddChildToCanvas(MainPanel);
    Slot->SetAnchors(FAnchors(0.5f, 0.5f, 0.5f, 0.5f));
    Slot->SetAlignment(FVector2D(0.5f, 0.5f));
    Slot->SetSize(FVector2D(400.f, 500.f));

    // Title
    UTextBlock* Title = WidgetTree->ConstructWidget<UTextBlock>(UTextBlock::StaticClass(), TEXT("PauseTitle"));
    Title->SetText(FText::FromString(TEXT("Paused")));
    FSlateFontInfo TitleFont = Title->GetFont();
    TitleFont.Size = 42;
    Title->SetFont(TitleFont);
    Title->SetJustification(ETextJustify::Center);
    Title->SetColorAndOpacity(FSlateColor(FLinearColor::White));
    UVerticalBoxSlot* TitleSlot = MainPanel->AddChildToVerticalBox(Title);
    TitleSlot->SetHorizontalAlignment(HAlign_Center);
    TitleSlot->SetPadding(FMargin(0.f, 0.f, 0.f, 30.f));

    // Buttons
    UButton* ResumeBtn = CreateMenuButton(TEXT("Resume"), MainPanel);
    ResumeBtn->OnClicked.AddDynamic(this, &UInsimulPauseMenuWidget::OnResumeClicked);

    UButton* SaveBtn = CreateMenuButton(TEXT("Save Game"), MainPanel);
    SaveBtn->OnClicked.AddDynamic(this, &UInsimulPauseMenuWidget::OnSaveGameClicked);

    UButton* LoadBtn = CreateMenuButton(TEXT("Load Game"), MainPanel);
    LoadBtn->OnClicked.AddDynamic(this, &UInsimulPauseMenuWidget::OnLoadGameClicked);

    UButton* SettingsBtn = CreateMenuButton(TEXT("Settings"), MainPanel);
    SettingsBtn->OnClicked.AddDynamic(this, &UInsimulPauseMenuWidget::OnSettingsClicked);

    UButton* QuitBtn = CreateMenuButton(TEXT("Quit to Main Menu"), MainPanel);
    QuitBtn->OnClicked.AddDynamic(this, &UInsimulPauseMenuWidget::OnQuitToMenuClicked);
}

void UInsimulPauseMenuWidget::BuildSaveLoadPanel(bool bIsSaveMode)
{
    bCurrentlySaveMode = bIsSaveMode;

    // Destroy previous save/load panel if it exists
    if (SaveLoadPanel)
    {
        SaveLoadPanel->RemoveFromParent();
        SaveLoadPanel = nullptr;
    }

    SaveLoadPanel = WidgetTree->ConstructWidget<UVerticalBox>(UVerticalBox::StaticClass(), TEXT("SaveLoadPanel"));
    UCanvasPanelSlot* Slot = RootCanvas->AddChildToCanvas(SaveLoadPanel);
    Slot->SetAnchors(FAnchors(0.5f, 0.5f, 0.5f, 0.5f));
    Slot->SetAlignment(FVector2D(0.5f, 0.5f));
    Slot->SetSize(FVector2D(450.f, 550.f));

    // Title
    SaveLoadTitle = WidgetTree->ConstructWidget<UTextBlock>(UTextBlock::StaticClass(), TEXT("SaveLoadTitle"));
    SaveLoadTitle->SetText(FText::FromString(bIsSaveMode ? TEXT("Save Game") : TEXT("Load Game")));
    FSlateFontInfo TitleFont = SaveLoadTitle->GetFont();
    TitleFont.Size = 36;
    SaveLoadTitle->SetFont(TitleFont);
    SaveLoadTitle->SetJustification(ETextJustify::Center);
    SaveLoadTitle->SetColorAndOpacity(FSlateColor(FLinearColor::White));
    UVerticalBoxSlot* TitleSlot = SaveLoadPanel->AddChildToVerticalBox(SaveLoadTitle);
    TitleSlot->SetHorizontalAlignment(HAlign_Center);
    TitleSlot->SetPadding(FMargin(0.f, 0.f, 0.f, 20.f));

    // Generate slot buttons
    for (int32 i = 0; i < MaxSaveSlots; ++i)
    {
        FString SlotName = FString::Printf(TEXT("InsimulSave_%d"), i);
        bool bSlotExists = UGameplayStatics::DoesSaveGameExist(SlotName, 0);

        FString Label;
        if (bSlotExists)
        {
            UInsimulSaveGame* ExistingSave = Cast<UInsimulSaveGame>(UGameplayStatics::LoadGameFromSlot(SlotName, 0));
            if (ExistingSave)
            {
                Label = FString::Printf(TEXT("Slot %d — %s"), i + 1, *ExistingSave->SaveDisplayName);
            }
            else
            {
                Label = FString::Printf(TEXT("Slot %d — Saved"), i + 1);
            }
        }
        else
        {
            Label = FString::Printf(TEXT("Slot %d — Empty"), i + 1);
        }

        UButton* SlotBtn = CreateMenuButton(Label, SaveLoadPanel);

        // For load mode, disable empty slots
        if (!bIsSaveMode && !bSlotExists)
        {
            SlotBtn->SetIsEnabled(false);
        }

        // Bind using a lambda captured delegate
        int32 CapturedIndex = i;
        if (bIsSaveMode)
        {
            SlotBtn->OnClicked.AddDynamic(this, &UInsimulPauseMenuWidget::OnSaveLoadBackClicked);
            // Override: use per-slot save via blueprint or C++ workaround
            FScriptDelegate Del;
            SlotBtn->OnClicked.Clear();
        }
    }

    // Back button
    UButton* BackBtn = CreateMenuButton(TEXT("Back"), SaveLoadPanel);
    BackBtn->OnClicked.AddDynamic(this, &UInsimulPauseMenuWidget::OnSaveLoadBackClicked);
}

UButton* UInsimulPauseMenuWidget::CreateMenuButton(const FString& Label, UVerticalBox* Parent)
{
    UButton* Btn = WidgetTree->ConstructWidget<UButton>(UButton::StaticClass());
    Btn->SetBackgroundColor(FLinearColor(0.12f, 0.12f, 0.18f, 0.9f));

    UTextBlock* BtnText = WidgetTree->ConstructWidget<UTextBlock>(UTextBlock::StaticClass());
    BtnText->SetText(FText::FromString(Label));
    FSlateFontInfo BtnFont = BtnText->GetFont();
    BtnFont.Size = 20;
    BtnText->SetFont(BtnFont);
    BtnText->SetJustification(ETextJustify::Center);
    BtnText->SetColorAndOpacity(FSlateColor(FLinearColor::White));
    Btn->AddChild(BtnText);

    UVerticalBoxSlot* BtnSlot = Parent->AddChildToVerticalBox(Btn);
    BtnSlot->SetHorizontalAlignment(HAlign_Center);
    BtnSlot->SetPadding(FMargin(0.f, 6.f, 0.f, 6.f));

    return Btn;
}

void UInsimulPauseMenuWidget::ShowMainPanel()
{
    MainPanel->SetVisibility(ESlateVisibility::Visible);
    if (SaveLoadPanel)
    {
        SaveLoadPanel->SetVisibility(ESlateVisibility::Collapsed);
    }
}

void UInsimulPauseMenuWidget::ShowSaveLoadPanel()
{
    MainPanel->SetVisibility(ESlateVisibility::Collapsed);
    if (SaveLoadPanel)
    {
        SaveLoadPanel->SetVisibility(ESlateVisibility::Visible);
    }
}

// ── Button handlers ──

void UInsimulPauseMenuWidget::OnResumeClicked()
{
    ClosePauseMenu();
}

void UInsimulPauseMenuWidget::OnSaveGameClicked()
{
    BuildSaveLoadPanel(true);
    ShowSaveLoadPanel();
}

void UInsimulPauseMenuWidget::OnLoadGameClicked()
{
    BuildSaveLoadPanel(false);
    ShowSaveLoadPanel();
}

void UInsimulPauseMenuWidget::OnSettingsClicked()
{
    // Settings panel would be shown here — reuses the same pattern as main menu settings
    UE_LOG(LogTemp, Log, TEXT("[InsimulPauseMenu] Settings requested"));
}

void UInsimulPauseMenuWidget::OnQuitToMenuClicked()
{
    SetPaused(false);
    UGameplayStatics::OpenLevel(this, TEXT("MainMenuLevel"));
}

void UInsimulPauseMenuWidget::OnSaveSlotClicked(int32 SlotIndex)
{
    FString SlotName = FString::Printf(TEXT("InsimulSave_%d"), SlotIndex);
    UInsimulSaveGame* SaveInstance = Cast<UInsimulSaveGame>(UGameplayStatics::CreateSaveGameObject(UInsimulSaveGame::StaticClass()));
    if (!SaveInstance) return;

    // Populate save data from current game state
    APawn* PlayerPawn = GetOwningPlayerPawn();
    if (PlayerPawn)
    {
        SaveInstance->PlayerLocation = PlayerPawn->GetActorLocation();
        SaveInstance->PlayerRotation = PlayerPawn->GetActorRotation();
    }

    SaveInstance->SaveDisplayName = FDateTime::Now().ToString(TEXT("%Y-%m-%d %H:%M"));

    UGameplayStatics::SaveGameToSlot(SaveInstance, SlotName, 0);
    UE_LOG(LogTemp, Log, TEXT("[InsimulPauseMenu] Game saved to slot %d"), SlotIndex);

    // Refresh the panel to show updated slot info
    BuildSaveLoadPanel(true);
    ShowSaveLoadPanel();
}

void UInsimulPauseMenuWidget::OnLoadSlotClicked(int32 SlotIndex)
{
    FString SlotName = FString::Printf(TEXT("InsimulSave_%d"), SlotIndex);
    UInsimulSaveGame* LoadedSave = Cast<UInsimulSaveGame>(UGameplayStatics::LoadGameFromSlot(SlotName, 0));
    if (!LoadedSave) return;

    // Restore player position
    APawn* PlayerPawn = GetOwningPlayerPawn();
    if (PlayerPawn)
    {
        PlayerPawn->SetActorLocation(LoadedSave->PlayerLocation);
        PlayerPawn->SetActorRotation(LoadedSave->PlayerRotation);
    }

    UE_LOG(LogTemp, Log, TEXT("[InsimulPauseMenu] Game loaded from slot %d"), SlotIndex);
    ClosePauseMenu();
}

void UInsimulPauseMenuWidget::OnSaveLoadBackClicked()
{
    ShowMainPanel();
}
