// Auto-generated by Insimul export pipeline — do not edit manually.
#include "InsimulMainMenuGameMode.h"
#include "InsimulMainMenuWidget.h"
#include "Kismet/GameplayStatics.h"

AInsimulMainMenuGameMode::AInsimulMainMenuGameMode()
{
    // No default pawn — this is a menu-only level
    DefaultPawnClass = nullptr;
}

void AInsimulMainMenuGameMode::BeginPlay()
{
    Super::BeginPlay();

    APlayerController* PC = UGameplayStatics::GetPlayerController(this, 0);
    if (!PC) return;

    // Show mouse cursor for menu interaction
    PC->bShowMouseCursor = true;
    PC->SetInputMode(FInputModeUIOnly());

    // Create and display the main menu widget
    MainMenuWidget = CreateWidget<UInsimulMainMenuWidget>(PC, UInsimulMainMenuWidget::StaticClass());
    if (MainMenuWidget)
    {
        MainMenuWidget->SetTitle(MenuTitle);
        MainMenuWidget->SetBackgroundImage(BackgroundImagePath);
        MainMenuWidget->AddToViewport();
    }
}
