// Auto-generated by Insimul export pipeline — do not edit manually.
#include "InsimulWorldMap.h"
#include "Kismet/GameplayStatics.h"
#include "Framework/Application/SlateApplication.h"
#include "Rendering/DrawElements.h"

// ─────────────────────────────────────────────
// Lifecycle
// ─────────────────────────────────────────────

void UInsimulWorldMap::NativeConstruct()
{
    Super::NativeConstruct();
    SetVisibility(ESlateVisibility::Collapsed);
}

void UInsimulWorldMap::NativeTick(const FGeometry& MyGeometry, float InDeltaTime)
{
    Super::NativeTick(MyGeometry, InDeltaTime);
}

// ─────────────────────────────────────────────
// Initialization
// ─────────────────────────────────────────────

void UInsimulWorldMap::InitializeMap(float InWorldSize, const TArray<float>& InZoomLevels)
{
    WorldSize = FMath::Max(InWorldSize, 1.f);
    ZoomLevels = InZoomLevels;
    if (ZoomLevels.Num() == 0)
    {
        ZoomLevels = { 0.5f, 1.f, 2.f, 4.f };
    }
    // Start at the first zoom level >= 1.0, or index 0
    CurrentZoomIndex = 0;
    for (int32 i = 0; i < ZoomLevels.Num(); ++i)
    {
        if (ZoomLevels[i] >= 1.f)
        {
            CurrentZoomIndex = i;
            break;
        }
    }
    PanOffset = FVector2D::ZeroVector;
}

// ─────────────────────────────────────────────
// Data population
// ─────────────────────────────────────────────

void UInsimulWorldMap::AddMarker(const FInsimulMapMarker& Marker)
{
    Markers.Add(Marker);
}

void UInsimulWorldMap::AddRoad(const FInsimulMapRoad& Road)
{
    Roads.Add(Road);
}

void UInsimulWorldMap::UpdatePlayerPosition(FVector2D Position, float RotationDegrees)
{
    PlayerPosition = Position;
    PlayerRotation = RotationDegrees;
}

void UInsimulWorldMap::ClearMarkersByType(EInsimulMapMarkerType Type)
{
    Markers.RemoveAll([Type](const FInsimulMapMarker& M) { return M.MarkerType == Type; });
}

// ─────────────────────────────────────────────
// Toggle & visibility
// ─────────────────────────────────────────────

void UInsimulWorldMap::ToggleMap()
{
    bIsOpen = !bIsOpen;

    if (bIsOpen)
    {
        SetVisibility(ESlateVisibility::Visible);
        // Pause game and show cursor
        UGameplayStatics::SetGamePaused(GetWorld(), true);
        APlayerController* PC = GetOwningPlayer();
        if (PC)
        {
            PC->bShowMouseCursor = true;
            FInputModeGameAndUI InputMode;
            InputMode.SetWidgetToFocus(TakeWidget());
            InputMode.SetLockMouseToViewportBehavior(EMouseLockMode::DoNotLock);
            PC->SetInputMode(InputMode);
        }
    }
    else
    {
        SetVisibility(ESlateVisibility::Collapsed);
        UGameplayStatics::SetGamePaused(GetWorld(), false);
        APlayerController* PC = GetOwningPlayer();
        if (PC)
        {
            PC->bShowMouseCursor = false;
            PC->SetInputMode(FInputModeGameOnly());
        }
        bIsDragging = false;
    }
}

// ─────────────────────────────────────────────
// Coordinate conversion
// ─────────────────────────────────────────────

FVector2D UInsimulWorldMap::WorldToMap(FVector2D WorldPos, const FGeometry& Geometry) const
{
    const FVector2D Size = Geometry.GetLocalSize();
    const float MapSize = FMath::Min(Size.X, Size.Y) - MAP_PADDING * 2.f;
    const float Zoom = ZoomLevels.IsValidIndex(CurrentZoomIndex) ? ZoomLevels[CurrentZoomIndex] : 1.f;

    // Normalise world position to [0,1]
    const float NormX = WorldPos.X / WorldSize;
    const float NormY = WorldPos.Y / WorldSize;

    // Apply zoom and pan
    const float CenterX = Size.X * 0.5f;
    const float CenterY = Size.Y * 0.5f;

    const float ScreenX = CenterX + (NormX - 0.5f) * MapSize * Zoom + PanOffset.X;
    const float ScreenY = CenterY + (NormY - 0.5f) * MapSize * Zoom + PanOffset.Y;

    return FVector2D(ScreenX, ScreenY);
}

// ─────────────────────────────────────────────
// Zoom
// ─────────────────────────────────────────────

void UInsimulWorldMap::CycleZoom(int32 Direction)
{
    const int32 NewIndex = CurrentZoomIndex + Direction;
    if (NewIndex >= 0 && NewIndex < ZoomLevels.Num())
    {
        CurrentZoomIndex = NewIndex;
        ClampPanOffset();
    }
}

void UInsimulWorldMap::ClampPanOffset()
{
    const float Zoom = ZoomLevels.IsValidIndex(CurrentZoomIndex) ? ZoomLevels[CurrentZoomIndex] : 1.f;
    const float MaxPan = WorldSize * Zoom * 0.5f;
    PanOffset.X = FMath::Clamp(PanOffset.X, -MaxPan, MaxPan);
    PanOffset.Y = FMath::Clamp(PanOffset.Y, -MaxPan, MaxPan);
}

// ─────────────────────────────────────────────
// Input handling
// ─────────────────────────────────────────────

FReply UInsimulWorldMap::NativeOnMouseWheel(const FGeometry& InGeometry, const FPointerEvent& InMouseEvent)
{
    const float Delta = InMouseEvent.GetWheelDelta();
    CycleZoom(Delta > 0.f ? 1 : -1);
    return FReply::Handled();
}

FReply UInsimulWorldMap::NativeOnMouseButtonDown(const FGeometry& InGeometry, const FPointerEvent& InMouseEvent)
{
    if (InMouseEvent.GetEffectingButton() == EKeys::LeftMouseButton)
    {
        bIsDragging = true;
        DragStart = InMouseEvent.GetScreenSpacePosition();
        return FReply::Handled().CaptureMouse(TakeWidget());
    }
    return FReply::Unhandled();
}

FReply UInsimulWorldMap::NativeOnMouseButtonUp(const FGeometry& InGeometry, const FPointerEvent& InMouseEvent)
{
    if (InMouseEvent.GetEffectingButton() == EKeys::LeftMouseButton && bIsDragging)
    {
        bIsDragging = false;
        return FReply::Handled().ReleaseMouseCapture();
    }
    return FReply::Unhandled();
}

FReply UInsimulWorldMap::NativeOnMouseMove(const FGeometry& InGeometry, const FPointerEvent& InMouseEvent)
{
    if (bIsDragging)
    {
        const FVector2D CurrentPos = InMouseEvent.GetScreenSpacePosition();
        PanOffset += CurrentPos - DragStart;
        DragStart = CurrentPos;
        ClampPanOffset();
        return FReply::Handled();
    }
    return FReply::Unhandled();
}

// ─────────────────────────────────────────────
// Rendering
// ─────────────────────────────────────────────

int32 UInsimulWorldMap::NativePaint(const FPaintArgs& Args, const FGeometry& AllottedGeometry,
    const FSlateRect& MyCullingRect, FSlateWindowElementList& OutDrawElements,
    int32 LayerId, const FWidgetStyle& InWidgetStyle, bool bParentEnabled) const
{
    // Semi-transparent background overlay
    const FVector2D GeoSize = AllottedGeometry.GetLocalSize();
    FSlateDrawElement::MakeBox(
        OutDrawElements,
        LayerId,
        AllottedGeometry.ToPaintGeometry(),
        FCoreStyle::Get().GetBrush("WhiteBrush"),
        ESlateDrawEffect::None,
        FLinearColor(0.05f, 0.05f, 0.1f, 0.85f)
    );
    ++LayerId;

    // Title
    const FString Title = TEXT("WORLD MAP");
    FSlateFontInfo TitleFont = FCoreStyle::GetDefaultFontStyle("Bold", 24);
    FSlateDrawElement::MakeText(
        OutDrawElements,
        LayerId,
        AllottedGeometry.ToPaintGeometry(FVector2D(GeoSize.X * 0.5f - 60.f, 10.f), FVector2D(200.f, 40.f)),
        Title,
        TitleFont,
        ESlateDrawEffect::None,
        FLinearColor::White
    );

    // Draw roads
    const FSlateBrush* WhiteBrush = FCoreStyle::Get().GetBrush("WhiteBrush");
    for (const FInsimulMapRoad& Road : Roads)
    {
        for (int32 i = 0; i < Road.Waypoints.Num() - 1; ++i)
        {
            const FVector2D A = WorldToMap(Road.Waypoints[i], AllottedGeometry);
            const FVector2D B = WorldToMap(Road.Waypoints[i + 1], AllottedGeometry);
            TArray<FVector2D> LinePoints;
            LinePoints.Add(A);
            LinePoints.Add(B);
            FSlateDrawElement::MakeLines(
                OutDrawElements,
                LayerId,
                AllottedGeometry.ToPaintGeometry(),
                LinePoints,
                ESlateDrawEffect::None,
                FLinearColor(0.6f, 0.6f, 0.6f, 0.8f),
                true,
                FMath::Max(Road.Width * ROAD_LINE_THICKNESS, 1.f)
            );
        }
    }
    ++LayerId;

    // Draw markers
    for (const FInsimulMapMarker& Marker : Markers)
    {
        DrawMarker(Marker, AllottedGeometry, OutDrawElements, LayerId);
    }
    ++LayerId;

    // Draw player arrow
    {
        const FVector2D PlayerScreenPos = WorldToMap(PlayerPosition, AllottedGeometry);
        const float Rad = FMath::DegreesToRadians(PlayerRotation);
        const float ArrowLen = PLAYER_ARROW_SIZE;

        // Triangle: tip + two base corners
        const FVector2D Tip = PlayerScreenPos + FVector2D(FMath::Sin(Rad), -FMath::Cos(Rad)) * ArrowLen;
        const FVector2D BaseL = PlayerScreenPos + FVector2D(
            FMath::Sin(Rad + PI * 0.75f), -FMath::Cos(Rad + PI * 0.75f)) * ArrowLen * 0.6f;
        const FVector2D BaseR = PlayerScreenPos + FVector2D(
            FMath::Sin(Rad - PI * 0.75f), -FMath::Cos(Rad - PI * 0.75f)) * ArrowLen * 0.6f;

        TArray<FVector2D> Arrow;
        Arrow.Add(Tip);
        Arrow.Add(BaseL);
        Arrow.Add(BaseR);
        Arrow.Add(Tip); // close the triangle
        FSlateDrawElement::MakeLines(
            OutDrawElements,
            LayerId,
            AllottedGeometry.ToPaintGeometry(),
            Arrow,
            ESlateDrawEffect::None,
            FLinearColor(0.2f, 0.8f, 1.f, 1.f),
            true,
            2.f
        );
    }
    ++LayerId;

    // Legend
    const FSlateFontInfo LegendFont = FCoreStyle::GetDefaultFontStyle("Regular", 12);
    const float LegendY = GeoSize.Y - 80.f;
    const float LegendX = 20.f;
    FSlateDrawElement::MakeText(
        OutDrawElements,
        LayerId,
        AllottedGeometry.ToPaintGeometry(FVector2D(LegendX, LegendY), FVector2D(300.f, 20.f)),
        FString::Printf(TEXT("Zoom: %.1fx  |  Scroll to zoom  |  Drag to pan  |  M to close"),
            ZoomLevels.IsValidIndex(CurrentZoomIndex) ? ZoomLevels[CurrentZoomIndex] : 1.f),
        LegendFont,
        ESlateDrawEffect::None,
        FLinearColor(0.7f, 0.7f, 0.7f, 1.f)
    );

    return LayerId;
}

void UInsimulWorldMap::DrawMarker(const FInsimulMapMarker& Marker, const FGeometry& Geometry,
    FSlateWindowElementList& OutDrawElements, int32 LayerId) const
{
    const FVector2D Pos = WorldToMap(Marker.WorldPosition, Geometry);
    const float Size = (Marker.MarkerType == EInsimulMapMarkerType::Settlement) ? MARKER_SIZE * 1.5f : MARKER_SIZE;

    // Marker dot
    FSlateDrawElement::MakeBox(
        OutDrawElements,
        LayerId,
        Geometry.ToPaintGeometry(Pos - FVector2D(Size * 0.5f, Size * 0.5f), FVector2D(Size, Size)),
        FCoreStyle::Get().GetBrush("WhiteBrush"),
        ESlateDrawEffect::None,
        Marker.Color
    );

    // Label for settlements
    if (Marker.MarkerType == EInsimulMapMarkerType::Settlement && !Marker.Label.IsEmpty())
    {
        const FSlateFontInfo Font = FCoreStyle::GetDefaultFontStyle("Regular", 10);
        FSlateDrawElement::MakeText(
            OutDrawElements,
            LayerId + 1,
            Geometry.ToPaintGeometry(Pos + FVector2D(-30.f, Size * 0.5f + 2.f), FVector2D(100.f, 16.f)),
            Marker.Label,
            Font,
            ESlateDrawEffect::None,
            FLinearColor::White
        );
    }
}
