// Auto-generated by Insimul export pipeline — do not edit manually.
#include "InsimulSaveGame.h"

UInsimulSaveGame::UInsimulSaveGame()
{
    SaveDisplayName = TEXT("New Save");
    SaveTimestamp = FDateTime::Now();
    PlayerLocation = FVector::ZeroVector;
    PlayerRotation = FRotator::ZeroRotator;
}
