// Copyright 2024 Insimul. All Rights Reserved.
//
// UInsimulUIRegistry — the UE seam over the portable panel-registry core
// (Portable/InsimulUIRegistryModel.h, US-XU1). A creator-overridable UDataAsset
// that maps a stable panel KEY ("quest_journal", "inventory", "dialogue", …) to a
// UUserWidget class. The default asset (DA_InsimulUIRegistry) is generated by
// templates/scripts/GenerateInsimulContent.py, which registers each WBP_ widget it
// creates; a creator swaps ANY panel by pointing the UInsimulSettings reference at
// their own registry asset (or editing the default one).
//
// The resolution SEMANTICS (override wins over default, missing-key diagnostics)
// are proven UE-free by FInsimulUIRegistryModel — this class is the thin,
// syntax-gated Blueprint/UObject boundary that exposes them to CreateWidget<>().

#pragma once

#include "CoreMinimal.h"
#include "Engine/DataAsset.h"
#include "Blueprint/UserWidget.h"
#include "InsimulUIRegistry.generated.h"

/**
 * A creator-editable panel entry: the stable key plus the widget class serving it.
 * The default asset ships one entry per default-UI panel; a creator adds/edits an
 * entry (an entry for an existing key overrides the shipped default).
 */
USTRUCT(BlueprintType)
struct FInsimulPanelBinding
{
	GENERATED_BODY()

	/** Stable panel key (mirrors conformance/ui/registry-cases.json → panel_keys). */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Insimul|UI")
	FName PanelKey;

	/** The UUserWidget (typically a WBP_ Blueprint) class serving this panel. */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Insimul|UI", meta = (AllowAbstract = "false"))
	TSoftClassPtr<UUserWidget> WidgetClass;
};

/**
 * The default-runtime UI panel registry. Referenced from UInsimulSettings so a
 * creator can replace the whole set, or override individual panels in place.
 */
UCLASS(BlueprintType)
class INSIMULRUNTIME_API UInsimulUIRegistry : public UDataAsset
{
	GENERATED_BODY()

public:
	/** All panel bindings. A later entry for the same key wins (override layer). */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Insimul|UI")
	TArray<FInsimulPanelBinding> Panels;

	/** True if `PanelKey` resolves to a bound widget class. */
	UFUNCTION(BlueprintPure, Category = "Insimul|UI")
	bool HasPanel(FName PanelKey) const;

	/**
	 * Resolve the widget class for `PanelKey` (a later binding wins). Returns
	 * nullptr when the key is unknown or the class fails to load; logs a warning so
	 * a creator sees exactly which panel is unbound.
	 */
	UFUNCTION(BlueprintCallable, Category = "Insimul|UI")
	TSubclassOf<UUserWidget> ResolvePanelClass(FName PanelKey) const;

	/** Register / override a single panel at runtime (last write wins). */
	UFUNCTION(BlueprintCallable, Category = "Insimul|UI")
	void RegisterPanel(FName PanelKey, TSoftClassPtr<UUserWidget> WidgetClass);
};
